!-----------------------------------------------------------------------------
! This code is written by a code generator.
!
!      generator : ./avsdatalib_generator.rb
!   generated on : Tue Jun 10 12:08:44 +0900 2008
!      avsveclen : 7
!
!-----------------------------------------------------------------------------

module avsdatalib
!*****************************************************************************
! MODULE AVSDATALIB                 A Generator of AVS-Field Data File (*.fld)
!*****************************************************************************
  !___________________________________________________________________________
  !
  ! 2008.06.04  by Akira Kageyama (ESC) kage@jamstec.go.jp
  !   - Code generator.
  !   - Renamed gavs ==> avsdatalib
  !
  ! 2003.05.21  by Akira Kageyama (ESC)
  !   - Removed 'target_dir' funcion, for ES use.
  !   - Separated the gavs__fld routine into two part:
  !     for coordinate data and field data.
  !
  ! 2003.02.06  by Akira Kageyama (ESC)
  !   - Added ids4avs; removed IDS_TEMP (no more problem for ids=77).
  !   - Renamed makeAVs --> gavs.
  !
  ! 2003.02.04  by Akira Kageyama (ESC)
  !   makeAvs.f90
  !     I converted old f77maf-lib.f into fortran90 version.
  !     In the old version, you had to call a companion shell script.
  !     In this new version, everything is done as a f90 program. 
  !
  ! 1995.02.04  by Kageyama, Akira (NIFS)
  !   f77maf
  !     To make an AVS-field data file from a fortran code.
  !     
  !---------------------------------------------------------------------------
  ! Usage:
  !    call avsdatalib__coord(IDS_FOR_AVS,                      &
  !                           tag_coord,                        &
  !                           nr, nt, np,                       &
  !                           coord%x, coord%y, coord%z)
  !
  !    call avsdatalib__fld(IDS_FOR_AVS,                        &
  !                         tag_coord,                          &
  !                         tag_fld,                            &
  !                         nr, nt, np,                         &
  !                         data_avs_vel%x, 'vx',               &
  !                         data_avs_vel%y, 'vy',               &
  !                         data_avs_vel%z, 'vz',               &
  !                         data_avs_mag%x, 'bx',               &
  !                         data_avs_mag%y, 'by',               &
  !                         data_avs_mag%z, 'bz')
  !__________________________________________________________________________/
  !
  use constants, only: SP
  implicit none
  private
  public :: avsdatalib__coord,  &
            avsdatalib__fld


  interface avsdatalib__fld
    module procedure avs01f
    module procedure avs02f
    module procedure avs03f
    module procedure avs04f
    module procedure avs05f
    module procedure avs06f
    module procedure avs07f
  end interface


contains


!===============
!    Private    
!===============



  !______________________________________________________________________
  !                                                                      !
  subroutine avs01f(ids4avs,      &                                      !
                    tag_coord,    &                                      !
                    tag_fld,      &                                      !
                    n1, n2, n3,   &                                      !
                    vec01, lab01  &                                      !
                    )                                                    !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    character(len=*), intent(in) :: tag_coord, tag_fld
    integer, intent(in) :: n1, n2, n3
    real(SP), dimension(n1,n2,n3), intent(in) :: vec01
    character(len=*), intent(in) :: lab01
  !______________________________________________________________________/
  !
    integer :: nvec = 1

    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab01, vec01)

    open(ids4avs,file=tag_fld//'.fld',form='formatted')
      write(ids4avs,'(a)')     '# AVS field data, generated by avsdatalib.'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a,i5)')  'ndim = ', 3
      write(ids4avs,'(a,i5)')  'dim1 = ', n1
      write(ids4avs,'(a,i5)')  'dim2 = ', n2
      write(ids4avs,'(a,i5)')  'dim3 = ', n3
      write(ids4avs,'(a,i5)')  'nspace = ', 3
      write(ids4avs,'(a,i5)')  'veclen = ', nvec
      write(ids4avs,'(a)')     'data = float'
      write(ids4avs,'(a)')     'field = irregular'
      write(ids4avs,'(a)')     'label = '//lab01
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'coord 1 file='//tag_coord//'.x filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 2 file='//tag_coord//'.y filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 3 file='//tag_coord//'.z filetype=unformatted'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'variable 1 file='//tag_fld//'.'//lab01//' filetype=unformatted'
    close(ids4avs)

  end subroutine avs01f


  !______________________________________________________________________
  !                                                                      !
  subroutine avs02f(ids4avs,      &                                      !
                    tag_coord,    &                                      !
                    tag_fld,      &                                      !
                    n1, n2, n3,   &                                      !
                    vec01, lab01, &                                      !
                    vec02, lab02  &                                      !
                    )                                                    !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    character(len=*), intent(in) :: tag_coord, tag_fld
    integer, intent(in) :: n1, n2, n3
    real(SP), dimension(n1,n2,n3), intent(in) :: vec01
    real(SP), dimension(n1,n2,n3), intent(in) :: vec02
    character(len=*), intent(in) :: lab01
    character(len=*), intent(in) :: lab02
  !______________________________________________________________________/
  !
    integer :: nvec = 2

    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab01, vec01)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab02, vec02)

    open(ids4avs,file=tag_fld//'.fld',form='formatted')
      write(ids4avs,'(a)')     '# AVS field data, generated by avsdatalib.'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a,i5)')  'ndim = ', 3
      write(ids4avs,'(a,i5)')  'dim1 = ', n1
      write(ids4avs,'(a,i5)')  'dim2 = ', n2
      write(ids4avs,'(a,i5)')  'dim3 = ', n3
      write(ids4avs,'(a,i5)')  'nspace = ', 3
      write(ids4avs,'(a,i5)')  'veclen = ', nvec
      write(ids4avs,'(a)')     'data = float'
      write(ids4avs,'(a)')     'field = irregular'
      write(ids4avs,'(a)')     'label = '//lab01
      write(ids4avs,'(a)')     'label = '//lab02
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'coord 1 file='//tag_coord//'.x filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 2 file='//tag_coord//'.y filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 3 file='//tag_coord//'.z filetype=unformatted'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'variable 1 file='//tag_fld//'.'//lab01//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 2 file='//tag_fld//'.'//lab02//' filetype=unformatted'
    close(ids4avs)

  end subroutine avs02f


  !______________________________________________________________________
  !                                                                      !
  subroutine avs03f(ids4avs,      &                                      !
                    tag_coord,    &                                      !
                    tag_fld,      &                                      !
                    n1, n2, n3,   &                                      !
                    vec01, lab01, &                                      !
                    vec02, lab02, &                                      !
                    vec03, lab03  &                                      !
                    )                                                    !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    character(len=*), intent(in) :: tag_coord, tag_fld
    integer, intent(in) :: n1, n2, n3
    real(SP), dimension(n1,n2,n3), intent(in) :: vec01
    real(SP), dimension(n1,n2,n3), intent(in) :: vec02
    real(SP), dimension(n1,n2,n3), intent(in) :: vec03
    character(len=*), intent(in) :: lab01
    character(len=*), intent(in) :: lab02
    character(len=*), intent(in) :: lab03
  !______________________________________________________________________/
  !
    integer :: nvec = 3

    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab01, vec01)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab02, vec02)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab03, vec03)

    open(ids4avs,file=tag_fld//'.fld',form='formatted')
      write(ids4avs,'(a)')     '# AVS field data, generated by avsdatalib.'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a,i5)')  'ndim = ', 3
      write(ids4avs,'(a,i5)')  'dim1 = ', n1
      write(ids4avs,'(a,i5)')  'dim2 = ', n2
      write(ids4avs,'(a,i5)')  'dim3 = ', n3
      write(ids4avs,'(a,i5)')  'nspace = ', 3
      write(ids4avs,'(a,i5)')  'veclen = ', nvec
      write(ids4avs,'(a)')     'data = float'
      write(ids4avs,'(a)')     'field = irregular'
      write(ids4avs,'(a)')     'label = '//lab01
      write(ids4avs,'(a)')     'label = '//lab02
      write(ids4avs,'(a)')     'label = '//lab03
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'coord 1 file='//tag_coord//'.x filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 2 file='//tag_coord//'.y filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 3 file='//tag_coord//'.z filetype=unformatted'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'variable 1 file='//tag_fld//'.'//lab01//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 2 file='//tag_fld//'.'//lab02//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 3 file='//tag_fld//'.'//lab03//' filetype=unformatted'
    close(ids4avs)

  end subroutine avs03f


  !______________________________________________________________________
  !                                                                      !
  subroutine avs04f(ids4avs,      &                                      !
                    tag_coord,    &                                      !
                    tag_fld,      &                                      !
                    n1, n2, n3,   &                                      !
                    vec01, lab01, &                                      !
                    vec02, lab02, &                                      !
                    vec03, lab03, &                                      !
                    vec04, lab04  &                                      !
                    )                                                    !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    character(len=*), intent(in) :: tag_coord, tag_fld
    integer, intent(in) :: n1, n2, n3
    real(SP), dimension(n1,n2,n3), intent(in) :: vec01
    real(SP), dimension(n1,n2,n3), intent(in) :: vec02
    real(SP), dimension(n1,n2,n3), intent(in) :: vec03
    real(SP), dimension(n1,n2,n3), intent(in) :: vec04
    character(len=*), intent(in) :: lab01
    character(len=*), intent(in) :: lab02
    character(len=*), intent(in) :: lab03
    character(len=*), intent(in) :: lab04
  !______________________________________________________________________/
  !
    integer :: nvec = 4

    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab01, vec01)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab02, vec02)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab03, vec03)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab04, vec04)

    open(ids4avs,file=tag_fld//'.fld',form='formatted')
      write(ids4avs,'(a)')     '# AVS field data, generated by avsdatalib.'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a,i5)')  'ndim = ', 3
      write(ids4avs,'(a,i5)')  'dim1 = ', n1
      write(ids4avs,'(a,i5)')  'dim2 = ', n2
      write(ids4avs,'(a,i5)')  'dim3 = ', n3
      write(ids4avs,'(a,i5)')  'nspace = ', 3
      write(ids4avs,'(a,i5)')  'veclen = ', nvec
      write(ids4avs,'(a)')     'data = float'
      write(ids4avs,'(a)')     'field = irregular'
      write(ids4avs,'(a)')     'label = '//lab01
      write(ids4avs,'(a)')     'label = '//lab02
      write(ids4avs,'(a)')     'label = '//lab03
      write(ids4avs,'(a)')     'label = '//lab04
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'coord 1 file='//tag_coord//'.x filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 2 file='//tag_coord//'.y filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 3 file='//tag_coord//'.z filetype=unformatted'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'variable 1 file='//tag_fld//'.'//lab01//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 2 file='//tag_fld//'.'//lab02//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 3 file='//tag_fld//'.'//lab03//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 4 file='//tag_fld//'.'//lab04//' filetype=unformatted'
    close(ids4avs)

  end subroutine avs04f


  !______________________________________________________________________
  !                                                                      !
  subroutine avs05f(ids4avs,      &                                      !
                    tag_coord,    &                                      !
                    tag_fld,      &                                      !
                    n1, n2, n3,   &                                      !
                    vec01, lab01, &                                      !
                    vec02, lab02, &                                      !
                    vec03, lab03, &                                      !
                    vec04, lab04, &                                      !
                    vec05, lab05  &                                      !
                    )                                                    !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    character(len=*), intent(in) :: tag_coord, tag_fld
    integer, intent(in) :: n1, n2, n3
    real(SP), dimension(n1,n2,n3), intent(in) :: vec01
    real(SP), dimension(n1,n2,n3), intent(in) :: vec02
    real(SP), dimension(n1,n2,n3), intent(in) :: vec03
    real(SP), dimension(n1,n2,n3), intent(in) :: vec04
    real(SP), dimension(n1,n2,n3), intent(in) :: vec05
    character(len=*), intent(in) :: lab01
    character(len=*), intent(in) :: lab02
    character(len=*), intent(in) :: lab03
    character(len=*), intent(in) :: lab04
    character(len=*), intent(in) :: lab05
  !______________________________________________________________________/
  !
    integer :: nvec = 5

    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab01, vec01)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab02, vec02)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab03, vec03)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab04, vec04)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab05, vec05)

    open(ids4avs,file=tag_fld//'.fld',form='formatted')
      write(ids4avs,'(a)')     '# AVS field data, generated by avsdatalib.'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a,i5)')  'ndim = ', 3
      write(ids4avs,'(a,i5)')  'dim1 = ', n1
      write(ids4avs,'(a,i5)')  'dim2 = ', n2
      write(ids4avs,'(a,i5)')  'dim3 = ', n3
      write(ids4avs,'(a,i5)')  'nspace = ', 3
      write(ids4avs,'(a,i5)')  'veclen = ', nvec
      write(ids4avs,'(a)')     'data = float'
      write(ids4avs,'(a)')     'field = irregular'
      write(ids4avs,'(a)')     'label = '//lab01
      write(ids4avs,'(a)')     'label = '//lab02
      write(ids4avs,'(a)')     'label = '//lab03
      write(ids4avs,'(a)')     'label = '//lab04
      write(ids4avs,'(a)')     'label = '//lab05
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'coord 1 file='//tag_coord//'.x filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 2 file='//tag_coord//'.y filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 3 file='//tag_coord//'.z filetype=unformatted'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'variable 1 file='//tag_fld//'.'//lab01//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 2 file='//tag_fld//'.'//lab02//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 3 file='//tag_fld//'.'//lab03//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 4 file='//tag_fld//'.'//lab04//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 5 file='//tag_fld//'.'//lab05//' filetype=unformatted'
    close(ids4avs)

  end subroutine avs05f


  !______________________________________________________________________
  !                                                                      !
  subroutine avs06f(ids4avs,      &                                      !
                    tag_coord,    &                                      !
                    tag_fld,      &                                      !
                    n1, n2, n3,   &                                      !
                    vec01, lab01, &                                      !
                    vec02, lab02, &                                      !
                    vec03, lab03, &                                      !
                    vec04, lab04, &                                      !
                    vec05, lab05, &                                      !
                    vec06, lab06  &                                      !
                    )                                                    !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    character(len=*), intent(in) :: tag_coord, tag_fld
    integer, intent(in) :: n1, n2, n3
    real(SP), dimension(n1,n2,n3), intent(in) :: vec01
    real(SP), dimension(n1,n2,n3), intent(in) :: vec02
    real(SP), dimension(n1,n2,n3), intent(in) :: vec03
    real(SP), dimension(n1,n2,n3), intent(in) :: vec04
    real(SP), dimension(n1,n2,n3), intent(in) :: vec05
    real(SP), dimension(n1,n2,n3), intent(in) :: vec06
    character(len=*), intent(in) :: lab01
    character(len=*), intent(in) :: lab02
    character(len=*), intent(in) :: lab03
    character(len=*), intent(in) :: lab04
    character(len=*), intent(in) :: lab05
    character(len=*), intent(in) :: lab06
  !______________________________________________________________________/
  !
    integer :: nvec = 6

    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab01, vec01)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab02, vec02)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab03, vec03)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab04, vec04)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab05, vec05)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab06, vec06)

    open(ids4avs,file=tag_fld//'.fld',form='formatted')
      write(ids4avs,'(a)')     '# AVS field data, generated by avsdatalib.'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a,i5)')  'ndim = ', 3
      write(ids4avs,'(a,i5)')  'dim1 = ', n1
      write(ids4avs,'(a,i5)')  'dim2 = ', n2
      write(ids4avs,'(a,i5)')  'dim3 = ', n3
      write(ids4avs,'(a,i5)')  'nspace = ', 3
      write(ids4avs,'(a,i5)')  'veclen = ', nvec
      write(ids4avs,'(a)')     'data = float'
      write(ids4avs,'(a)')     'field = irregular'
      write(ids4avs,'(a)')     'label = '//lab01
      write(ids4avs,'(a)')     'label = '//lab02
      write(ids4avs,'(a)')     'label = '//lab03
      write(ids4avs,'(a)')     'label = '//lab04
      write(ids4avs,'(a)')     'label = '//lab05
      write(ids4avs,'(a)')     'label = '//lab06
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'coord 1 file='//tag_coord//'.x filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 2 file='//tag_coord//'.y filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 3 file='//tag_coord//'.z filetype=unformatted'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'variable 1 file='//tag_fld//'.'//lab01//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 2 file='//tag_fld//'.'//lab02//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 3 file='//tag_fld//'.'//lab03//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 4 file='//tag_fld//'.'//lab04//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 5 file='//tag_fld//'.'//lab05//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 6 file='//tag_fld//'.'//lab06//' filetype=unformatted'
    close(ids4avs)

  end subroutine avs06f


  !______________________________________________________________________
  !                                                                      !
  subroutine avs07f(ids4avs,      &                                      !
                    tag_coord,    &                                      !
                    tag_fld,      &                                      !
                    n1, n2, n3,   &                                      !
                    vec01, lab01, &                                      !
                    vec02, lab02, &                                      !
                    vec03, lab03, &                                      !
                    vec04, lab04, &                                      !
                    vec05, lab05, &                                      !
                    vec06, lab06, &                                      !
                    vec07, lab07  &                                      !
                    )                                                    !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    character(len=*), intent(in) :: tag_coord, tag_fld
    integer, intent(in) :: n1, n2, n3
    real(SP), dimension(n1,n2,n3), intent(in) :: vec01
    real(SP), dimension(n1,n2,n3), intent(in) :: vec02
    real(SP), dimension(n1,n2,n3), intent(in) :: vec03
    real(SP), dimension(n1,n2,n3), intent(in) :: vec04
    real(SP), dimension(n1,n2,n3), intent(in) :: vec05
    real(SP), dimension(n1,n2,n3), intent(in) :: vec06
    real(SP), dimension(n1,n2,n3), intent(in) :: vec07
    character(len=*), intent(in) :: lab01
    character(len=*), intent(in) :: lab02
    character(len=*), intent(in) :: lab03
    character(len=*), intent(in) :: lab04
    character(len=*), intent(in) :: lab05
    character(len=*), intent(in) :: lab06
    character(len=*), intent(in) :: lab07
  !______________________________________________________________________/
  !
    integer :: nvec = 7

    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab01, vec01)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab02, vec02)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab03, vec03)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab04, vec04)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab05, vec05)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab06, vec06)
    call write_3d_data(ids4avs,n1,n2,n3,tag_fld//'.'//lab07, vec07)

    open(ids4avs,file=tag_fld//'.fld',form='formatted')
      write(ids4avs,'(a)')     '# AVS field data, generated by avsdatalib.'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a,i5)')  'ndim = ', 3
      write(ids4avs,'(a,i5)')  'dim1 = ', n1
      write(ids4avs,'(a,i5)')  'dim2 = ', n2
      write(ids4avs,'(a,i5)')  'dim3 = ', n3
      write(ids4avs,'(a,i5)')  'nspace = ', 3
      write(ids4avs,'(a,i5)')  'veclen = ', nvec
      write(ids4avs,'(a)')     'data = float'
      write(ids4avs,'(a)')     'field = irregular'
      write(ids4avs,'(a)')     'label = '//lab01
      write(ids4avs,'(a)')     'label = '//lab02
      write(ids4avs,'(a)')     'label = '//lab03
      write(ids4avs,'(a)')     'label = '//lab04
      write(ids4avs,'(a)')     'label = '//lab05
      write(ids4avs,'(a)')     'label = '//lab06
      write(ids4avs,'(a)')     'label = '//lab07
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'coord 1 file='//tag_coord//'.x filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 2 file='//tag_coord//'.y filetype=unformatted'
      write(ids4avs,'(a)')  &
        'coord 3 file='//tag_coord//'.z filetype=unformatted'
      write(ids4avs,'(a)')     '#'
      write(ids4avs,'(a)')  &
        'variable 1 file='//tag_fld//'.'//lab01//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 2 file='//tag_fld//'.'//lab02//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 3 file='//tag_fld//'.'//lab03//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 4 file='//tag_fld//'.'//lab04//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 5 file='//tag_fld//'.'//lab05//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 6 file='//tag_fld//'.'//lab06//' filetype=unformatted'
      write(ids4avs,'(a)')  &
        'variable 7 file='//tag_fld//'.'//lab07//' filetype=unformatted'
    close(ids4avs)

  end subroutine avs07f

    

  !______________________________________________________________________
  !                                                                      !
  subroutine write_3d_data(ids4avs,n1,n2,n3,file_name,data)              !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    integer, intent(in) :: n1, n2, n3
    character(len=*), intent(in) :: file_name
    real(SP), dimension(n1,n2,n3), intent(in) :: data
  !______________________________________________________________________/
  !
    open(ids4avs,file=file_name,form='unformatted')
       write(ids4avs) data
    close(ids4avs)

  end subroutine write_3d_data


!==============
!    Public    
!==============


  !______________________________________________________________________
  !                                                                      !
  subroutine avsdatalib__coord(ids4avs, tag_coord,      &                !
                               n1, n2, n3,              &                !
                               x, y, z)                                  !
  !______________________________________________________________________!
  !
    integer, intent(in) :: ids4avs
    character(len=*), intent(in) :: tag_coord
    integer, intent(in) :: n1, n2, n3
    real(SP), dimension(n1,n2,n3), intent(in) :: x, y, z
  !______________________________________________________________________/
  !
    call write_3d_data(ids4avs, n1, n2, n3, tag_coord//'.x', x)
    call write_3d_data(ids4avs, n1, n2, n3, tag_coord//'.y', y)
    call write_3d_data(ids4avs, n1, n2, n3, tag_coord//'.z', z)

  end subroutine avsdatalib__coord

end module avsdatalib
